name: 'Continuous Integration'
description: 'The CI step to lint, test and build python code'
inputs:
  service-name:
    required: true
    description: "Service Name to Build and Deploy"
  dockerhub-username:
    required: true
    description: "Service Name to Build and Deploy"
  dockerhub-token:
    required: true
    description: "Service Name to Build and Deploy"
  path:
    required: true
    description: "Service Name to Build and Deploy"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vikramshinde/${{ inputs.service-name }}:latest
      shell: bash
      working-directory: ${{ inputs.path}}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Push the Docker image
      run: docker push vikramshinde/${{ inputs.service-name }}:latest
      shell: bash