apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-retail-app
  name: sample-retail-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-retail-app
  type: NodePort