apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service1
  name: service1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: vikramshinde/service1:latest
        ports:
          - containerPort: 8080