name: Service11 Docker Image CI

on:
  push:
    paths:
      - 'source/service1/**'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_APP_NAME: xyz-demo-shop
  GKE_SERVICE: "service1"
  GKE_SERVICE_ACCOUNT: xyz-serviceaccount
  GKE_DEPLOYMENT_NAME: xyz-demo-shop-deployment
  GKE_REGION: europe-west2

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Service CI
        uses: ./.github/reusable_workflows/service_ci
        with:
          service-name: ${{ env.GKE_SERVICE }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          path: "source/service1/"

#  Deploy:
#    runs-on: ubuntu-latest
#    needs: Build
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Service CD
#        uses: ./.github/reusable_workflows/service_cd
#        with:
#          service-name: ${{ env.GKE_SERVICE }}
#          cluster_name: ${{ env.GKE_CLUSTER }}
#          location: ${{ env.GKE_REGION }}
#          credentials: ${{ secrets.GKE_SA_KEY }}
#          path: "source/service1/"